/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Inventario.Linea;
import Inventario.Marca;
import Inventario.Mecanica;
import Inventario.Modelo;
import Inventario.Repuesto;
import Inventario.Tipo;
import Inventario.Uso;

/**
 *
 * @author HernandezMartinez
 */
public class CargarDatos extends javax.swing.JDialog {

    /**
     * Creates new form CargarDatos
     *
     * @param parent
     * @param modal
     */
    public CargarDatos(java.awt.Frame parent, boolean modal) {

        super(parent, modal);
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        AreaCarga = new javax.swing.JTextArea();
        BtnCargar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cargar Datos");

        AreaCarga.setColumns(20);
        AreaCarga.setRows(5);
        jScrollPane1.setViewportView(AreaCarga);

        BtnCargar.setText("Cargar");
        BtnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCargarActionPerformed(evt);
            }
        });

        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnCargar, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(BtnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed

        this.setVisible(false);
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);

    }//GEN-LAST:event_BtnCancelarActionPerformed

    public static int contadorTipo = 0;
    public static int contadorModelo = 0;
    public static int contadorMarca = 0;
    public static int contadorLinea = 0;
    public static int contadorUso = 0;
    public static int contadorMecanica = 0;
    public static int contadorRepuesto = 0;

    public static Tipo[] tipo = new Tipo[50];
    public static Modelo[] modelo = new Modelo[50];
    public static Marca[] marca = new Marca[50];
    public static Linea[] linea = new Linea[50];
    public static Uso[] uso = new Uso[50];
    public static Mecanica[] mecanica = new Mecanica[50];
    public static Repuesto[] repuesto = new Repuesto[50];


    private void BtnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCargarActionPerformed

        String datos = AreaCarga.getText();
        String[] datoscargados = datos.split("\n");

        for (String info : datoscargados) {

            String[] datosfinales = info.split(",");

            switch (datosfinales[0]) {

                case "TIPO":
                    Tipo local = new Tipo(datosfinales[1], datosfinales[2]);
                    tipo[contadorTipo] = local;
                    contadorTipo++;
                    break;

                case "MODELO":
                    Modelo local2 = new Modelo(Integer.parseInt(datosfinales[1]), datosfinales[2]);
                    modelo[contadorModelo] = local2;
                    contadorModelo++;
                    break;

                case "MARCA":
                    Marca local3 = new Marca(datosfinales[1], datosfinales[2]);
                    marca[contadorMarca] = local3;
                    contadorMarca++;
                    break;

                case "LINEA":
                    Linea local4 = new Linea(datosfinales[1], datosfinales[2]);
                    linea[contadorLinea] = local4;
                    contadorLinea++;
                    break;

                case "USO":
                    Uso local5 = new Uso(datosfinales[1], datosfinales[2]);
                    uso[contadorUso] = local5;
                    contadorUso++;
                    break;

                case "MECANICA":
                    Mecanica local6 = new Mecanica(datosfinales[1], datosfinales[2]);
                    mecanica[contadorMecanica] = local6;
                    contadorMecanica++;
                    break;

                case "REPUESTO":
                    Repuesto local7 = new Repuesto(datosfinales[1], datosfinales[2]);
                    repuesto[contadorRepuesto] = local7;
                    contadorRepuesto++;
                    break;

            }

        }


    }//GEN-LAST:event_BtnCargarActionPerformed

    public void agregarTipo(Tipo obj) {

        for (int i = 0; i < 50; i++) {

            if (tipo[i] == null) {
                tipo[i] = obj;
                return;

            }

        }

    }

    public void agregarModelo(Modelo obj) {

        for (int i = 0; i < 50; i++) {

            if (modelo[i] == null) {
                modelo[i] = obj;
                return;

            }

        }

    }

    public void agregarMarca(Marca obj) {

        for (int i = 0; i < 50; i++) {

            if (marca[i] == null) {
                marca[i] = obj;
                return;

            }

        }

    }

    public void agregarLinea(Linea obj) {

        for (int i = 0; i < 50; i++) {

            if (linea[i] == null) {
                linea[i] = obj;
                return;

            }

        }

    }

    public void agregarUso(Uso obj) {

        for (int i = 0; i < 50; i++) {

            if (uso[i] == null) {
                uso[i] = obj;
                return;

            }

        }

    }

    public void agregarMecanica(Mecanica obj) {

        for (int i = 0; i < 50; i++) {

            if (mecanica[i] == null) {
                mecanica[i] = obj;
                return;

            }

        }

    }

    public void agregarRepuesto(Repuesto obj) {

        for (int i = 0; i < 50; i++) {

            if (repuesto[i] == null) {
                repuesto[i] = obj;
                return;

            }

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaCarga;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnCargar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
