/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author HernandezMartinez
 */
public class MenuAsegurado extends javax.swing.JDialog {

    /**
     * Creates new form MenuAsegurado
     */
    Date fecha = new Date();

    public MenuAsegurado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        JInfo.setEnabled(false);

        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        String fechaTexto = formatter.format(fecha);
        JFecha.setText("Fecha: " + fechaTexto);

    }

    public String ObtenerNombre(String Dpi) {
        String nombre = "";

        for (int i = 0; i < Solicitudes.seguro.length; i++) {

            if (Dpi.equals(Solicitudes.seguro[i].getDPI()) && Solicitudes.seguro[i] != null) {
                nombre = Solicitudes.seguro[i].getNombre();
                break;
            }
        }
        return nombre;
    }

    public String ObtenerApellido(String Dpi) {
        String apellido = "";

        for (int i = 0; i < Solicitudes.seguro.length; i++) {
            if (Dpi.equals(Solicitudes.seguro[i].getDPI()) && Solicitudes.seguro[i] != null) {
                apellido = Solicitudes.seguro[i].getApellido();
                break;
            }
        }
        return apellido;
    }

    public String ObtenerTelefon(String Dpi) {
        String telefono = "";

        for (int i = 0; i < Solicitudes.seguro.length; i++) {
            if (Dpi.equals(Solicitudes.seguro[i].getDPI()) && Solicitudes.seguro[i] != null) {
                telefono = Solicitudes.seguro[i].getTelefono();
                break;
            }
        }

        return telefono;
    }

    public String ObtenerDPI(String Dpi) {
        String DPI = "";

        for (int i = 0; i < Solicitudes.seguro.length; i++) {
            if (Dpi.equals(Solicitudes.seguro[i].getDPI()) && Solicitudes.seguro[i] != null) {
                DPI = Solicitudes.seguro[i].getDPI();
                break;
            }
        }
        return DPI;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnCerrarSesion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JInfo = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnMisSeguros = new javax.swing.JButton();
        BtnPagos = new javax.swing.JButton();
        BtnMisIncidentes = new javax.swing.JButton();
        JFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu Asegurado");

        BtnCerrarSesion.setText("Cerrar Sesión . . .");
        BtnCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarSesionActionPerformed(evt);
            }
        });

        JInfo.setColumns(20);
        JInfo.setForeground(new java.awt.Color(255, 255, 255));
        JInfo.setRows(5);
        JInfo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(JInfo);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Asegurado.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pago.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Advertencia.png"))); // NOI18N

        BtnMisSeguros.setText("Mis Seguros");
        BtnMisSeguros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMisSegurosActionPerformed(evt);
            }
        });

        BtnPagos.setText("Pagos");

        BtnMisIncidentes.setText("Mis Incidentes");
        BtnMisIncidentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMisIncidentesActionPerformed(evt);
            }
        });

        JFecha.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(JFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnMisSeguros, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnMisIncidentes, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnPagos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BtnCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(JFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnMisSeguros)
                    .addComponent(BtnPagos)
                    .addComponent(BtnMisIncidentes))
                .addGap(0, 33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnMisIncidentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMisIncidentesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnMisIncidentesActionPerformed

    private void BtnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarSesionActionPerformed

        this.setVisible(false);
        MenuPrincipal cierre = new MenuPrincipal();
        cierre.setVisible(true);

    }//GEN-LAST:event_BtnCerrarSesionActionPerformed

    private void BtnMisSegurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMisSegurosActionPerformed

        this.setVisible(false);
        MisSeguros seguros = new MisSeguros();
        seguros.setVisible(true);

    }//GEN-LAST:event_BtnMisSegurosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAsegurado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAsegurado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAsegurado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAsegurado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuAsegurado dialog = new MenuAsegurado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCerrarSesion;
    private javax.swing.JButton BtnMisIncidentes;
    private javax.swing.JButton BtnMisSeguros;
    private javax.swing.JButton BtnPagos;
    private javax.swing.JLabel JFecha;
    public javax.swing.JTextArea JInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
